services:
  web:
    build: .
    ports:
      - "5000:5000"
    container_name: flask_app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: ["flask", "run", "--host=0.0.0.0"]  # Ensures Flask listens on all interfaces

  redis:
    image: redis:alpine  # Lightweight Redis image
    ports:
      - "6379:6379"
    container_name: redis

